export enum EnvConstant {
  NODE_ENV = 'NODE_ENV',

  APP_NAME = 'APP_NAME',
  PORT = 'PORT',
  PREFIX = 'PREFIX',

  DATABASE_URL = 'DATABASE_URL',

  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',

  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_BUCKET_NAME = 'AWS_BUCKET_NAME',

  MAIL_HOST = 'MAIL_HOST',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  MAIL_FROM_ADDRESS = 'MAIL_FROM_ADDRESS',
  MAIL_FROM_NAME = 'MAIL_FROM_NAME',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_USERNAME = 'REDIS_USERNAME',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  CACHE_TTL = 'CACHE_TTL',

  ENC_PASSWORD = 'ENC_PASSWORD',

  CLIENT_URL = 'CLIENT_URL',
}
